matrix:
  include:
    - language: node_js
      node_js:
        - "8"
        - "10"
      script:
        - yarn build
        - yarn lint
        - yarn test-travis

    - language: node_js
      node_js: "8"
      stage: integ
      script:
        - yarn test-integ
