language: node_js
node_js:
  - '8'
  - '10'
script:
  - if [ "$TO_TEST" = "regular" ]; then yarn test-benchmark && yarn test-travis; fi
  - if [ "$TO_TEST" = "integration" ]; then yarn test-integration; fi
cache: yarn
git:
  depth: 5
env:
  - TO_TEST=regular
  - TO_TEST=integration
notifications:
  email:
    recipients:
      - tensorflowjs-build@google.com
    on_success: never
    on_failure: always
    on_pull_requests: false
matrix:
  exclude:
  - node_js: '8'
    env: TO_TEST=integration
